### ISSUE TITLE
Nicknames and Genders

### ISSUE THREAD

**Issue by AarCon** [afnleaf/pkautocalc#6]
Hey I noticed that when a pokemon has a nickname and a gender, the calc fails to parse that information. My initial thought is that the parser isn't working with the double set of parentheses. Here's an example mon that this will fail with:

Monke (Rillaboom) (F) @ Assault Vest  

Thanks for making this btw. It's a really powerful tool for planning shifts in the meta easier.

**Comment by afnleaf** [comment]
Good catch! Fixed here -> https://github.com/afnleaf/pkautocalc/commit/54a38f477526938eccae31258995a17880583cf4

I had coded it so that it worked with `Monke (F) (Rillaboom) @ Assault Vest` for some reason, which is not how showdown formats the paste. I didn't test it properly....

Thank you for the kind words! Let me know if you find anything else that needs fixing, I'm sure there are a lot of bugs.
